all:
    # Install database locally
	python setup.py

interactive:
    # Install database as an interactive framework
	pip install -e .

install:
    # Install database to the Python site-packages
	python -m pip install .
