MODEL:
  META_ARCHITECTURE: "HybridRetinaUNet"
  REQUIRE_SEMANTIC_SEGMENTATION: True
  WEIGHTED_BOX_TRAINING: True

  RPN:
    PRE_NMS_TOP_N_TRAIN: 1000
    POST_NMS_TOP_N_TRAIN: 1000
    PRE_NMS_TOP_N_TEST: 100
    POST_NMS_TOP_N_TEST: 10
    NMS_THRESH: 0.2
    POSITIVE_FRACTION: 0.33
    # Anchor generation
    ASPECT_RATIOS: (1.,)

    CUSTOM_ANCHORS: (((3, 9, 9), (2, 12, 13), (4, 17, 20), (1, 8, 8), (1, 32, 32)), ((3, 18, 18), (2, 24, 26), (3, 34, 40), (1, 16, 16), (1, 64, 64)), ((6, 36, 36), (4, 48, 52), (8, 68, 80), (2, 32, 32), (2, 128, 128)), ((12, 72, 72), (8, 96, 104), (16, 136, 160), (4, 64, 64), (4, 256, 256)), ((12, 144, 144), (8, 192, 208), (16, 272, 320), (4, 128, 128), (4, 512, 512)))
    ANCHOR_SIZES: ((), (), (), (), ())
    ANCHOR_DEPTHS: ((), (), (), (), ())

    BATCH_SIZE_PER_IMAGE: 16384
    MATCHER: "ATSSMatcher"
    ATSS_NUM_CANDIDATES: 30

  RETINANET:
    INFERENCE_TH: 0.6
    TWO_STAGE: False
    SELECTED_FEATURE_MAPS: [ 2, 3, 4, 5, 6 ]
    KEEP_LARGEST_CC_CLASSES: [ 3, ]
    DUST_THRESHOLDS: [ 400, 0 ]

  ROI_BOX_HEAD:
    REGRESSION_LOSS: "CIoULoss"

INPUT:
  N_DIM: 3
  N_CHANNELS: 1
  N_OBJ_CLASSES: 4
  N_UNIQUE_OBJ_CLASSES: 2
  N_REL_CLASSES: 4
  N_IMG_ATT_CLASSES: 5
  N_ATT_CLASSES: 5
  MIN_SIZE: (1, 1, 1)
  TRANSFORM_SCHEME: "HeadCT"
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  VERTICAL_FLIP_PROB_TRAIN: 0.5
  DEPTH_FLIP_PROB_TRAIN: 0.5
  AFFINE_MAX_TRANSLATE: (0, 40, 40)
  AFFINE_SCALE_RANGE: ((1., 1.), (0.8, 1.2), (0.8, 1.2))

  AFFINE_MAX_ROTATE: (180, 15,15)

  CLIP_MIN: -50.
  CLIP_MAX: 150.

DATASETS:
  TRAIN: ("INSTANCE2022",)
  VAL: ("INSTANCE2022",)
  TEST: ("INSTANCE2022", "MZ", "BHSD", "CQ500")
  FOLD: 0
  EVALUATION_PARAMETERS: "default_3d"

SOLVER:
  BASE_LR: 0.01
  STEPS: (9000, 18000)
  MAX_ITER: 24000
  CHECKPOINT_PERIOD: 1000
  METERS_PERIOD: 1000
  IMS_PER_BATCH: 1

  MOMENTUM: 0.9
  WEIGHT_DECAY: 3e-5
  # Start with BASE_LR * WARMUP_FACTOR = 1e-6 LR and ramp up linearly to BASE_LR
  WARMUP_FACTOR: 1e-4
  WARMUP_ITERS: 6500
  # Will multiply the LR by GAMMA**#MILESTONE i.e. after each STEPS bracket, LR is divided by 10
  GAMMA: 0.1


DATALOADER:
  ASPECT_RATIO_GROUPING: False
  SIZE_DIVISIBILITY: (32, 64, 64)
  NUM_WORKERS: 0
  KNOWLEDGE_GUIDED_BOX_GROUPING: True
  STRICT_SAMPLING: True

TEST:
  IMS_PER_BATCH: 1
  DO_PRETRAIN_VAL: False
  TRACK_VAL_LOSS: True
  VAL_PERIOD: 1000

  COCO:
    PER_CATEGORY_METRICS: True

  RELATION:
    IOU_THRESHOLD: 0.3  # IoU threshold for metrics
    RECALL_AT_K: [ 2, 5, 10 ]
    COMPUTE_RELATION_UPPER_BOUND: True
    UPPER_BOUND_ALLOW_RECLASSIFICATION: False

OUTPUT_DIR: "./output/detec_INST_only_long_kg_strict/"
