all:
    # Install fed_scene_graph_prediction locally
	python setup.py

interactive:
    # Install fed_scene_graph_prediction as an interactive framework
	pip install -e .

install:
    # Install fed_scene_graph_prediction to the Python site-packages
	python -m pip install .
