all:
    # Install scene_graph_api locally
	python setup.py

interactive:
    # Install scene_graph_api as an interactive framework
	pip install -e .

install:
    # Install scene_graph_api to the Python site-packages
	python -m pip install .
