all:
    # Install scene_graph_annotation locally
	python setup.py

interactive:
    # Install scene_graph_annotation as an interactive framework
	pip install -e .

install:
    # Install scene_graph_annotation to the Python site-packages
	python -m pip install .
