OUTPUT_DIR: "./output/{out_dir}/PC/MOTIF_{run_idx}_bias_init"

MODEL:
  META_ARCHITECTURE: "HybridRetinaUNet"
  MASK_ON: False
  REQUIRE_SEMANTIC_SEGMENTATION: True
  WEIGHTED_BOX_TRAINING: False
  RELATION_ON: True
  PRETRAINED_DETECTOR_CKPT: "./output/{out_dir}/{src}_detec_other{run_idx}/model_final.pth"
  OPTIMIZED_ROI_HEADS_PIPELINE: True

  RPN:
    PRE_NMS_TOP_N_TRAIN: 1000
    POST_NMS_TOP_N_TRAIN: 1000
    PRE_NMS_TOP_N_TEST: 100
    POST_NMS_TOP_N_TEST: 10
    NMS_THRESH: 0.2
    POSITIVE_FRACTION: 0.33
    # Anchor generation
    ASPECT_RATIOS: (1.,)

    CUSTOM_ANCHORS: (((3, 9, 9), (2, 12, 13), (4, 17, 20), (1, 8, 8), (1, 32, 32)), ((3, 18, 18), (2, 24, 26), (3, 34, 40), (1, 16, 16), (1, 64, 64)), ((6, 36, 36), (4, 48, 52), (8, 68, 80), (2, 32, 32), (2, 128, 128)), ((12, 72, 72), (8, 96, 104), (16, 136, 160), (4, 64, 64), (4, 256, 256)), ((12, 144, 144), (8, 192, 208), (16, 272, 320), (4, 128, 128), (4, 512, 512)))
    ANCHOR_SIZES: ((), (), (), (), ())
    ANCHOR_DEPTHS: ((), (), (), (), ())

    BATCH_SIZE_PER_IMAGE: 16384
    MATCHER: "ATSSMatcher"
    ATSS_NUM_CANDIDATES: 30

  RETINANET:
    INFERENCE_TH: 0.6
    TWO_STAGE: False
    SELECTED_FEATURE_MAPS: [ 2, 3, 4, 5, 6 ]
    KEEP_LARGEST_CC_CLASSES: [ 3, ]
    DUST_THRESHOLDS: [ 400, 0 ]

  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "DownScaleConvFeatureExtractor"
    POOLER_RESOLUTION: 8
    POOLER_RESOLUTION_DEPTH: 4
    FEATURE_REPRESENTATION_SIZE: 64

    ADD_GTBOX_TO_PROPOSAL_IN_TRAIN: False
    REMOVE_OBJ_NO_MATCH: False

  ROI_HEADS:
    FG_IOU_THRESHOLD: 0.3

  ROI_RELATION_HEAD:
    USE_GT_BOX: True
    USE_GT_OBJECT_LABEL: True
    DISABLE_RECLASSIFICATION: True
    BATCH_SIZE_PER_IMAGE: 6
    REQUIRE_BOX_OVERLAP: False
    REQUIRE_REL_IN_TRAIN: True
    NUM_SAMPLE_PER_GT_REL: 4
    POSITIVE_WEIGHT: 0.75

    IS_SLOW_PREDICTOR_HEAD: False
    LABEL_SMOOTHING_LOSS: False
    PREDICT_USE_BIAS: True

    PREDICT_USE_MASKS: True

    EMBED_DIM: 200  # Because of glove
    CONTEXT_HIDDEN_DIM: 128
    CONTEXT_POOLING_DIM: 512

    CONTEXT_DROPOUT_RATE: 0.2

    PREDICTOR: "MotifPredictor"

INPUT:
  N_DIM: 3
  N_CHANNELS: 1
  N_OBJ_CLASSES: 4
  N_UNIQUE_OBJ_CLASSES: 2
  N_REL_CLASSES: 4
  N_IMG_ATT_CLASSES: 5
  N_ATT_CLASSES: 5
  MIN_SIZE: (1, 1, 1)
  TRANSFORM_SCHEME: "HeadCT"
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  VERTICAL_FLIP_PROB_TRAIN: 0.5
  DEPTH_FLIP_PROB_TRAIN: 0.5
  AFFINE_MAX_TRANSLATE: (0, 40, 40)
  AFFINE_SCALE_RANGE: ((1., 1.), (0.8, 1.2), (0.8, 1.2))

  AFFINE_MAX_ROTATE: (15, 15,15)

  CLIP_MIN: -100.
  CLIP_MAX: 300.

DATASETS:
  TRAIN: ({train_ds},)
  VAL: ("INSTANCE2022_rel", "MZ_rel", "BHSD_rel", "CQ500_rel")
  TEST: ("INSTANCE2022_rel", "MZ_rel", "BHSD_rel", "CQ500_rel")
  FOLD: 0
  EVALUATION_PARAMETERS: "default_3d"
  STATISTICS_OVERRIDE: "INSTANCE2022_relMZ_relBHSD_relCQ500_rel_statistics.cache"

SOLVER:
  BASE_LR: 0.0001
  STEPS: (120,140)
  MAX_ITER: 200
  CHECKPOINT_PERIOD: 20
  METERS_PERIOD: 20
  IMS_PER_BATCH: 13

  MOMENTUM: 0.9
  WEIGHT_DECAY: 3e-5
  WARMUP_FACTOR: .01
  WARMUP_ITERS: 50
  GAMMA: 0.1


DATALOADER:
  ASPECT_RATIO_GROUPING: False
  SIZE_DIVISIBILITY: (32, 64, 64)
  NUM_WORKERS: 0

TEST:
  IMS_PER_BATCH: 1
  DO_PRETRAIN_VAL: False
  TRACK_VAL_LOSS: True
  VAL_PERIOD: 20

  COCO:
    PER_CATEGORY_METRICS: True

  RELATION:
    LATER_NMS_PREDICTION_THRES: 0.99  # No NMS
    IOU_THRESHOLD: 0.3  # IoU threshold for metrics
    RECALL_AT_K: [ 2, 5, 8, 10 ]
